//  Copyright © 2019 Foursquare. All rights reserved.

#ifndef PilgrimConstants_h
#define PilgrimConstants_h

#import <Foundation/Foundation.h>


FOUNDATION_EXPORT NSString *const ADDRESS;

FOUNDATION_EXPORT NSString *const ARRIVAL;

FOUNDATION_EXPORT NSString *const ARRIVAL_EVENT_NAME;

FOUNDATION_EXPORT NSString *const ARRIVAL_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const CATERGORY_IDS;

FOUNDATION_EXPORT NSString *const CITY;

FOUNDATION_EXPORT NSString *const CONFIDENCE;

FOUNDATION_EXPORT NSString *const COUNTRY;

FOUNDATION_EXPORT NSString *const CROSSSTREET;

FOUNDATION_EXPORT NSString *const DEPARTURE;

FOUNDATION_EXPORT NSString *const DEPARTURE_EVENT_NAME;

FOUNDATION_EXPORT NSString *const DEPARTURE_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const EVENT_LAT;

FOUNDATION_EXPORT NSString *const EVENT_LNG;

FOUNDATION_EXPORT NSString *const EVENT_SOURCE;

FOUNDATION_EXPORT NSString *const GEOFENCE_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const GEOFENCE_ENTER_EVENT_NAME;

FOUNDATION_EXPORT NSString *const GEOFENCE_ENTER_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const GEOFENCE_DWELL_EVENT_NAME;

FOUNDATION_EXPORT NSString *const GEOFENCE_DWELL_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const GEOFENCE_CONFIRM_EVENT_NAME;

FOUNDATION_EXPORT NSString *const GEOFENCE_CONFIRM_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const GEOFENCE_EXIT_EVENT_NAME;

FOUNDATION_EXPORT NSString *const GEOFENCE_EXIT_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const GEOFENCE_LAT;

FOUNDATION_EXPORT NSString *const GEOFENCE_LNG;

FOUNDATION_EXPORT NSString *const HISTORICAL;

FOUNDATION_EXPORT NSString *const HISTORICAL_EVENT_NAME;

FOUNDATION_EXPORT NSString *const HISTORICAL_EVENT_TYPE;

FOUNDATION_EXPORT NSString *const LAT;

FOUNDATION_EXPORT NSString *const LNG;

FOUNDATION_EXPORT NSString *const LOCATION_TYPE;

FOUNDATION_EXPORT NSString *const PARTNER_VENUE_ID;

FOUNDATION_EXPORT NSString *const PRIMARY_CATEGORY_ID;

FOUNDATION_EXPORT NSString *const PRIMARY_CATEGORY_NAME;

FOUNDATION_EXPORT NSString *const PRIMARY_CHAIN_ID;

FOUNDATION_EXPORT NSString *const PRIMARY_CHAIN_NAME;

FOUNDATION_EXPORT NSString *const PROBABILITY;

FOUNDATION_EXPORT NSString *const RADIUS;

FOUNDATION_EXPORT NSString *const STATE;

FOUNDATION_EXPORT NSString *const SUPERVENUE_ID;

FOUNDATION_EXPORT NSString *const SUPERVENUE_NAME;

FOUNDATION_EXPORT NSString *const SUPERVENUE_PRIMARY_CATEGORY_ID;

FOUNDATION_EXPORT NSString *const SUPERVENUE_PRIMARY_CATEGORY_NAME;

FOUNDATION_EXPORT NSString *const TIMESTAMP;

FOUNDATION_EXPORT NSString *const VENUE_ID;

FOUNDATION_EXPORT NSString *const VENUE_NAME;

FOUNDATION_EXPORT NSString *const VENUE_CHAIN_IDS;

FOUNDATION_EXPORT NSString *const VISIT_ID;

FOUNDATION_EXPORT NSString *const VISIT_TYPE;

FOUNDATION_EXPORT NSString *const ZIP_CODE;

#endif
